---
- hosts: localhost
  become: true

  tasks:
  - name: configure login banner
    copy:
      content: |
        ============================================================================================================
        This Ansible Tower Appliance (Powered by Red Hat) is available at IP address {{ ansible_default_ipv4.address }}
        ============================================================================================================
        .
      dest: "{{ item }}"
    loop:
      - /etc/issue
      - /etc/issue.net
  - name: configure vim settings for YAML
    copy:
      content: "autocmd FileType yaml setlocal ai ts=2 sw=2 et"
      dest: "{{ item }}"
    loop:
      - ~/.vimrc
      - ~root/.vimrc
